import { useAppSelector } from '@/data/hook';
import { authSelector } from '@/data/slicer/authSlicer';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  const auth = useAppSelector(authSelector);

  useEffect(() => {
    console.log(auth);
  }, [auth.user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">
          <div>
            <h1>HomePage</h1>{' '}
          </div>
        </div>
      </main>
    </>
  );
}
