import { useAppDispatch, useAppSelector } from '@/data/hook';
import { User } from '@/data/models/auth.models';
import { authSelector, profile } from '@/data/slicer/authSlicer';
import Head from 'next/head';
import { useEffect, useState } from 'react';

export default function Home() {
  const dispatch = useAppDispatch();
  const auth = useAppSelector(authSelector);
  const [user, setUser] = useState<User>();
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    setUser(auth.user);
    setLoading(auth.loading);
  }, [auth]);

  function getUser() {
    dispatch(profile());
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">
          <div>
            <h1>HomePage</h1> <br />
            <button onClick={getUser}>Check User with Token</button>
            <br />
            <br /> {loading && <div>Loading...</div>}
            {user && !loading && <span>{JSON.stringify(user)}</span>}
          </div>
        </div>
      </main>
    </>
  );
}
